import torch
import torch.nn as nn
import os

# --- 1. Architecture (Must match your trained brain!) ---
class myS3Brain(nn.Module):
    def __init__(self):
        super().__init__()
        self.myConv1 = nn.Conv2d(3, 8, kernel_size=5, stride=4, padding=2)
        self.myConv2 = nn.Conv2d(8, 16, kernel_size=3, stride=2, padding=1)
        self.myHidden = nn.Linear(25600, 32)
        self.myActivation = nn.ReLU()
        self.myOutput = nn.Linear(32, 3) 

    def forward(self, x):
        # We don't need the forward logic just to export, 
        # but we keep the structure for consistency.
        pass

# --- 2. Load the Weights ---
myModel = myS3Brain()
myWeightFile = "torch13-Validated-Model.pth"

if os.path.exists(myWeightFile):
    myModel.load_state_dict(torch.load(myWeightFile))
    print(f"Successfully loaded: {myWeightFile}")
else:
    print(f"Error: Could not find {myWeightFile}. Train it first!")
    exit()

# --- 3. The Export Logic ---
def myExportToHeader(myModel, myFilename="myWeights.h"):
    print(f"Exporting to {myFilename}...")
    
    with open(myFilename, "w") as f:
        # Header Guards
        f.write("#ifndef MY_WEIGHTS_H\n")
        f.write("#define MY_WEIGHTS_H\n\n")
        f.write("// TinyTorch Weights for ESP32-S3\n")
        f.write("// Generated by torch15.py\n\n")
        
        # Loop through every named piece of the brain (Weights and Biases)
        for name, param in myModel.named_parameters():
            # Convert name like 'myConv1.weight' to 'myConv1_weight'
            myCleanName = name.replace(".", "_")
            
            # Flatten the multi-dimensional math into one long list of numbers
            myData = param.detach().cpu().numpy().flatten()
            
            # Write the C++ array
            f.write(f"const float {myCleanName}[] = {{\n    ")
            
            # Convert each number to a string with 8 decimal places
            myValues = [f"{val:.8f}f" for val in myData]
            
            # Join them with commas and wrap lines every 8 numbers for readability
            for i in range(0, len(myValues), 8):
                f.write(", ".join(myValues[i:i+8]))
                if i + 8 < len(myValues):
                    f.write(",\n    ")
            
            f.write("\n};\n\n")
            print(f" -> Exported {myCleanName} ({len(myData)} values)")

        f.write("#endif // MY_WEIGHTS_H\n")

    print("\nDone! You now have a C++ header file ready for the ESP32-S3.")

myExportToHeader(myModel)